### ISSUE TITLE
Repository on Google Code is unavailable

### ISSUE THREAD

**Issue by decioluckow** [domdorn/spring-security-facelets-taglib#5]
The url http://spring-security-facelets-taglib.googlecode.com/svn/repo/ is returning 404, other repository will be available?

**Comment by domdorn** [comment]
we've moved two days ago to github. plan is to push the lib to maven central in the weekend, see also #1

**Comment by vinyfalcao** [comment]
Do you have any estimate of when it had been available ?

**Comment by domdorn** [comment]
just started refactoring. needs a few commits before its ready to be pushed to maven central.

**Comment by domdorn** [comment]
please see discussion in 
https://github.com/domdorn/spring-security-facelets-taglib/issues/6
